name: Publish Docker Hub

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]   # semver tags create release images too

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Test
        run: dotnet test --no-build -c Release --logger "trx;LogFileName=test-results.trx"

  publish:
    name: Build & Push Images
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: authservice
            context: Portal/AuthService
            dockerfile: Portal/AuthService/Dockerfile
            image: ${{ secrets.DOCKERHUB_USERNAME }}/fdms-authservice
          - name: employeeservice
            context: Portal/EmployeeService
            dockerfile: Portal/EmployeeService/Dockerfile
            image: ${{ secrets.DOCKERHUB_USERNAME }}/fdms-employeeservice
          - name: documentservice
            context: Portal/DocumentService
            dockerfile: Portal/DocumentService/Dockerfile
            image: ${{ secrets.DOCKERHUB_USERNAME }}/fdms-documentservice
          - name: claimservice
            context: Portal/ClaimService
            dockerfile: Portal/ClaimService/Dockerfile
            image: ${{ secrets.DOCKERHUB_USERNAME }}/fdms-claimservice
          - name: apigateway
            context: Portal/CentralAPIGateway
            dockerfile: Portal/CentralAPIGateway/Dockerfile
            image: ${{ secrets.DOCKERHUB_USERNAME }}/fdms-apigateway

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=short,prefix=sha-
            type=ref,event=tag    # v1.2.3 -> :1.2.3
            type=ref,event=branch # main -> :main
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
